project:
  type: website

website:
  title: "StanBio"
  favicon: stan-logo.png
  twitter-card: true
  site-url: https://stanbio.github.io/
  navbar:
    logo: images/Favicon_48.png
    left:
      - href: index.qmd
        text: Home
      - abstracts.qmd
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



